/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Microsoft_YaHei_Mono16.c                              *
* Font:        Microsoft YaHei Mono                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\2. STM32CubeMX\1. STM32F107VCT6\10. LCD+STemwin½ø½×\2. STemWin_WM\2. STemwin_WM_Button\STemWinLibrary522\Font\unicode_lib.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoft_YaHei_Mono16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoft_YaHei_Mono16_6309[ 48] = { /* code 6309 */
  0x0C, 0x01, 0x80, 0x00,
  0x0C, 0x00, 0xC0, 0x00,
  0x0C, 0x7F, 0xFF, 0x40,
  0xBF, 0xA0, 0x02, 0x40,
  0x0C, 0x03, 0x00, 0x00,
  0x0E, 0x06, 0x00, 0x00,
  0x2D, 0x7F, 0xFF, 0x80,
  0x9C, 0x1C, 0x0C, 0x00,
  0x0C, 0x38, 0x34, 0x00,
  0x0C, 0x07, 0xF0, 0x00,
  0x0C, 0x0B, 0xAD, 0x00,
  0xB8, 0xE4, 0x02, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoft_YaHei_Mono16_94AE[ 48] = { /* code 94AE */
  0x0C, 0x3F, 0xFF, 0x00,
  0x28, 0x03, 0x03, 0x00,
  0x7F, 0x83, 0x03, 0x00,
  0x90, 0x02, 0x03, 0x00,
  0x3F, 0x42, 0x03, 0x00,
  0x0C, 0x3F, 0xFF, 0x00,
  0x0C, 0x06, 0x02, 0x00,
  0xBF, 0xC6, 0x02, 0x00,
  0x0C, 0x06, 0x02, 0x00,
  0x0C, 0x86, 0x02, 0x00,
  0x0F, 0x05, 0x06, 0x00,
  0x08, 0x7F, 0xFF, 0x80
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontMicrosoft_YaHei_Mono16_CharInfo[2] = {
   {  13,  12,   0,   1,  13, acGUI_FontMicrosoft_YaHei_Mono16_6309 } /* code 6309 */
  ,{  13,  12,   0,   1,  13, acGUI_FontMicrosoft_YaHei_Mono16_94AE } /* code 94AE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoft_YaHei_Mono16_Prop2 = {
   0x94AE /* first character */
  ,0x94AE /* last character  */
  ,&GUI_FontMicrosoft_YaHei_Mono16_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoft_YaHei_Mono16_Prop1 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontMicrosoft_YaHei_Mono16_CharInfo[  0] /* address of first character */
  ,&GUI_FontMicrosoft_YaHei_Mono16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoft_YaHei_Mono16 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMicrosoft_YaHei_Mono16_Prop1}
  ,11 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

