/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: YaHeiConsolasHybrid28.c                               *
* Font:        YaHei Consolas Hybrid                                 *
* Height:      28                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  28                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\2°¢STM32CubeMX\STM32F107VCT6\5°¢LCD\4°¢STemWinœ‘ æ∫∫◊÷_ex\STemWinLibrary522\font\Name_etc.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYaHeiConsolasHybrid28;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontYaHeiConsolasHybrid28_5B9D[ 84] = { /* code 5B9D */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,__XX____,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XX_____,________,__XX____,
  _XX_____,________,__XX____,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,__X_____,________,
  ________,__X___XX,________,
  ________,__X___XX,X_______,
  ________,__X____X,X_______,
  ________,__X____X,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHeiConsolasHybrid28_5F20[ 84] = { /* code 5F20 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__X_____,________,
  _XXXXXX_,__X_____,__X_____,
  ______X_,__X_____,_XX_____,
  ______X_,__X____X,XX______,
  ______X_,__X___XX,X_______,
  _XXXXXX_,__X_XXX_,________,
  _XX___X_,__X__X__,________,
  _XX_____,__X_____,________,
  _XX____X,XXXXXXXX,XXXX____,
  _XX_____,__X__XX_,________,
  _XXXXXX_,__X___X_,________,
  ______X_,__X___XX,________,
  ______X_,__X____X,________,
  ______X_,__X____X,X_______,
  _____XX_,__X_____,XX______,
  _____XX_,__X___X_,_X______,
  _____XX_,__X_XX__,__XX____,
  _XXXXX__,__XX____,___X____,
  ________,_XX_____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHeiConsolasHybrid28_63A7[ 84] = { /* code 63A7 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,_____XX_,________,
  ___XX___,XXXXXXXX,XXXX____,
  XXXXXXX_,X_______,__XX____,
  ___XX___,X_______,__XX____,
  ___XX___,X__X___X,__XX____,
  ___XX___,__XX___X,XX______,
  ___XX___,_XX_____,_XX_____,
  ___XXXX_,XX______,__XX____,
  __XXX__X,X_______,___X____,
  XX_XX___,________,________,
  ___XX___,XXXXXXXX,XXXX____,
  ___XX___,_____XX_,________,
  ___XX___,_____XX_,________,
  ___XX___,_____XX_,________,
  ___XX___,_____XX_,________,
  ___XX___,_____XX_,________,
  ___XX__X,XXXXXXXX,XXXXX___,
  _XXX____,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHeiConsolasHybrid28_6D4B[ 84] = { /* code 6D4B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __X_____,________,__XX____,
  __XX__XX,XXXXX__X,X_XX____,
  ___XX_X_,____X__X,X_XX____,
  ______X_,____X__X,X_XX____,
  ______X_,_X__X__X,X_XX____,
  _X____X_,_X__X__X,X_XX____,
  _XX___X_,_X__X__X,X_XX____,
  __XX__X_,_X__X__X,X_XX____,
  ___X__X_,_X__X__X,X_XX____,
  ______X_,_X__X__X,X_XX____,
  ______X_,_X__X__X,X_XX____,
  ___X__X_,_X__X__X,X_XX____,
  ___X__X_,XX__X__X,X_XX____,
  __XX____,XX_____X,X_XX____,
  __XX____,XXX_____,__XX____,
  __X____X,X_XX____,__XX____,
  _XX___XX,___XX___,__XX____,
  _XX__XX_,____XX__,__XX____,
  _XX_X___,_____X_X,XXX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHeiConsolasHybrid28_901A[ 84] = { /* code 901A */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __X_____,________,________,
  __XX___X,XXXXXXXX,XXX_____,
  ___XX___,_______X,XX______,
  ___XX___,_XX___XX,________,
  ____X___,__XXXXX_,________,
  _______X,XXXXXXXX,XXX_____,
  _______X,X___XX__,__X_____,
  XXXX___X,X___XX__,__X_____,
  ___X___X,XXXXXXXX,XXX_____,
  ___X___X,X___XX__,__X_____,
  ___X___X,X___XX__,__X_____,
  ___X___X,X___XX__,__X_____,
  ___X___X,XXXXXXXX,XXX_____,
  ___X___X,X___XX__,__X_____,
  ___X___X,X___XX__,__X_____,
  ___X___X,X___XXXX,XXX_____,
  __XXX___,________,________,
  _XX_XX__,________,________,
  _X____XX,XXXXXXXX,XXXX____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontYaHeiConsolasHybrid28_CharInfo[5] = {
   {  24,  24,  3, acGUI_FontYaHeiConsolasHybrid28_5B9D } /* code 5B9D */
  ,{  24,  24,  3, acGUI_FontYaHeiConsolasHybrid28_5F20 } /* code 5F20 */
  ,{  24,  24,  3, acGUI_FontYaHeiConsolasHybrid28_63A7 } /* code 63A7 */
  ,{  24,  24,  3, acGUI_FontYaHeiConsolasHybrid28_6D4B } /* code 6D4B */
  ,{  24,  24,  3, acGUI_FontYaHeiConsolasHybrid28_901A } /* code 901A */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHeiConsolasHybrid28_Prop5 = {
   0x901A /* first character */
  ,0x901A /* last character  */
  ,&GUI_FontYaHeiConsolasHybrid28_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHeiConsolasHybrid28_Prop4 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontYaHeiConsolasHybrid28_CharInfo[  3] /* address of first character */
  ,&GUI_FontYaHeiConsolasHybrid28_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHeiConsolasHybrid28_Prop3 = {
   0x63A7 /* first character */
  ,0x63A7 /* last character  */
  ,&GUI_FontYaHeiConsolasHybrid28_CharInfo[  2] /* address of first character */
  ,&GUI_FontYaHeiConsolasHybrid28_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHeiConsolasHybrid28_Prop2 = {
   0x5F20 /* first character */
  ,0x5F20 /* last character  */
  ,&GUI_FontYaHeiConsolasHybrid28_CharInfo[  1] /* address of first character */
  ,&GUI_FontYaHeiConsolasHybrid28_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHeiConsolasHybrid28_Prop1 = {
   0x5B9D /* first character */
  ,0x5B9D /* last character  */
  ,&GUI_FontYaHeiConsolasHybrid28_CharInfo[  0] /* address of first character */
  ,&GUI_FontYaHeiConsolasHybrid28_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontYaHeiConsolasHybrid28 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,28 /* height of font  */
  ,28 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontYaHeiConsolasHybrid28_Prop1}
  ,22 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

