/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Microsoft YaHei Mono16.c                              *
* Font:        Microsoft YaHei Mono                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\2. STM32CubeMX\1. STM32F107VCT6\10. LCD+STemwin½ø½×\2. STemWin_WM\2. STemwin_WM_Button\STemWinLibrary522\Font\unicode_lib.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftYaHeiMono16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono16_4E2D[ 32] = { /* code 4E2D */
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  _XXXXXXX,XXX_____,
  _X___XX_,__X_____,
  _X___XX_,__X_____,
  _X___XX_,__X_____,
  _XXXXXXX,XXX_____,
  _X___XX_,__X_____,
  _____XX_,________,
  _____XX_,________,
  _____XX_,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono16_6309[ 32] = { /* code 6309 */
  ________,________,
  ________,________,
  __X____X,________,
  __X____X,________,
  __X_XXXX,XXX_____,
  XXXXX___,________,
  __X___XX,________,
  __XXXXXX,XXXX____,
  XXX__X__,_X______,
  __X__X__,_X______,
  __X___XX,X_______,
  __X___XX,XX______,
  XX_XXX__,__XX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono16_6587[ 32] = { /* code 6587 */
  ________,________,
  ________,________,
  _____X__,________,
  ______X_,________,
  XXXXXXXX,XXXX____,
  ___X____,X_______,
  ___X____,X_______,
  ___X____,X_______,
  ____X__X,________,
  _____XX_,________,
  _____XX_,________,
  ___XX__X,X_______,
  XXX_____,_XX_____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono16_82F1[ 32] = { /* code 82F1 */
  ________,________,
  ________,________,
  ___X____,X_______,
  XXXXXXXX,XXXX____,
  ___X____,X_______,
  _____X__,________,
  __XXXXXX,XX______,
  __X__X__,_X______,
  __X__X__,_X______,
  XXXXXXXX,XXXX____,
  _____XX_,________,
  ___XX__X,X_______,
  XXX_____,_XXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono16_94AE[ 32] = { /* code 94AE */
  ________,________,
  ________,________,
  __X__XXX,XXX_____,
  _XXX__X_,__X_____,
  _X____X_,__X_____,
  XXXX__X_,__X_____,
  __X___X_,__X_____,
  __X__XXX,XXX_____,
  XXXXX_X_,__X_____,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XX__X_,__X_____,
  __X_XXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMicrosoftYaHeiMono16_CharInfo[5] = {
   {  12,  12,  2, acGUI_FontMicrosoftYaHeiMono16_4E2D } /* code 4E2D */
  ,{  12,  12,  2, acGUI_FontMicrosoftYaHeiMono16_6309 } /* code 6309 */
  ,{  12,  12,  2, acGUI_FontMicrosoftYaHeiMono16_6587 } /* code 6587 */
  ,{  12,  12,  2, acGUI_FontMicrosoftYaHeiMono16_82F1 } /* code 82F1 */
  ,{  12,  12,  2, acGUI_FontMicrosoftYaHeiMono16_94AE } /* code 94AE */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono16_Prop5 = {
   0x94AE /* first character */
  ,0x94AE /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono16_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono16_Prop4 = {
   0x82F1 /* first character */
  ,0x82F1 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono16_CharInfo[  3] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono16_Prop3 = {
   0x6587 /* first character */
  ,0x6587 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono16_CharInfo[  2] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono16_Prop2 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono16_CharInfo[  1] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono16_Prop1 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono16_CharInfo[  0] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftYaHeiMono16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMicrosoftYaHeiMono16_Prop1}
  ,12 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

