/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Microsoft YaHei UI22.c                                *
* Font:        Microsoft YaHei UI                                    *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\2. STM32CubeMX\1. STM32F107VCT6\10. LCD+STemwin½ø½×\2. STemWin_WM\2. STemwin_WM_Button\STemWinLibrary522\Font\unicode_lib.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftYaHeiUI22;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiUI22_6309[ 64] = { /* code 6309 */
  0x0C, 0x00, 0x08, 0x00,
  0x0C, 0x00, 0x0C, 0x00,
  0x0C, 0x00, 0x0C, 0x00,
  0x0C, 0x0F, 0xFF, 0xFF,
  0xFF, 0xCC, 0x00, 0x03,
  0x0C, 0x0C, 0x20, 0x03,
  0x0C, 0x00, 0xA0, 0x00,
  0x0C, 0x00, 0xD0, 0x00,
  0x1F, 0xCF, 0xFF, 0xFF,
  0xFC, 0x03, 0x40, 0x30,
  0x0C, 0x0B, 0x00, 0x60,
  0x0C, 0x0B, 0x90, 0xC0,
  0x0C, 0x00, 0x7F, 0x40,
  0x0C, 0x00, 0x2F, 0x80,
  0x0C, 0x06, 0xD0, 0x78,
  0xF8, 0xB8, 0x00, 0x0A
};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiUI22_94AE[ 60] = { /* code 94AE */
  0x08, 0x00, 0x00, 0x00,
  0x18, 0x0F, 0xFF, 0xF4,
  0x3F, 0xC0, 0x50, 0x24,
  0x20, 0x00, 0x50, 0x24,
  0x90, 0x00, 0x90, 0x24,
  0xBF, 0xC0, 0x90, 0x24,
  0x0C, 0x00, 0x90, 0x20,
  0x0C, 0x0F, 0xFF, 0xF0,
  0xFF, 0xF0, 0x80, 0x30,
  0x0C, 0x00, 0xC0, 0x30,
  0x0C, 0x00, 0xC0, 0x30,
  0x0C, 0x00, 0xC0, 0x30,
  0x0C, 0x60, 0xC0, 0x30,
  0x0F, 0xD0, 0xC0, 0x30,
  0x09, 0x3F, 0xFF, 0xFC
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontMicrosoftYaHeiUI22_CharInfo[2] = {
   {  16,  16,   0,   3,  17, acGUI_FontMicrosoftYaHeiUI22_6309 } /* code 6309 */
  ,{  15,  15,   1,   3,  17, acGUI_FontMicrosoftYaHeiUI22_94AE } /* code 94AE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftYaHeiUI22_Prop2 = {
   0x94AE /* first character */
  ,0x94AE /* last character  */
  ,&GUI_FontMicrosoftYaHeiUI22_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMicrosoftYaHeiUI22_Prop1 = {
   0x6309 /* first character */
  ,0x6309 /* last character  */
  ,&GUI_FontMicrosoftYaHeiUI22_CharInfo[  0] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiUI22_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftYaHeiUI22 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMicrosoftYaHeiUI22_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

