/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: YaHei_Mono28.c                                        *
* Font:        Microsoft YaHei Mono                                  *
* Height:      28                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  28                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\9. Œ¢—ı∑÷Œˆ“«_STM32\Code-By-G_Z\3. Œ¢—ı∑÷Œˆ“«V0.1\STemWinLibrary522\Font\main_window.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei_Mono28;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_4EEA[112] = { /* code 4EEA */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  _____XX_,_____X__,________,________,
  _____XX_,_____XX_,________,________,
  _____XX_,XX___XX_,___XX___,________,
  ____XX__,XX___XXX,___XX___,________,
  ____XX__,_X____XX,___XX___,________,
  ____X___,_XX___XX,___XX___,________,
  ___XX___,_XX_____,__XX____,________,
  ___XX___,_XX_____,__XX____,________,
  __XXX___,__X_____,__XX____,________,
  _XXXX___,__XX____,_XXX____,________,
  _XXXX___,__XX____,_XX_____,________,
  _X_XX___,___XX___,XXX_____,________,
  ___XX___,___XX___,XX______,________,
  ___XX___,____XX_X,XX______,________,
  ___XX___,_____XXX,X_______,________,
  ___XX___,_____XXX,________,________,
  ___XX___,____XXXX,X_______,________,
  ___XX___,___XXX_X,XX______,________,
  ___XX___,_XXXX___,XXX_____,________,
  ___XX___,XXXX____,_XXXX___,________,
  ___XX_XX,XX______,___XXXX_,________,
  ___XX__X,________,____XX__,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_5206[112] = { /* code 5206 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,X____X__,________,________,
  _______X,X____XX_,________,________,
  _______X,X____XX_,________,________,
  ______XX,______XX,________,________,
  _____XX_,_______X,X_______,________,
  ____XXX_,_______X,XX______,________,
  ___XXX__,________,XXX_____,________,
  __XXX___,________,_XXX____,________,
  _XXX____,________,__XXX___,________,
  XXX_____,________,___XXXX_,________,
  _X_XXXXX,XXXXXXXX,XX___X__,________,
  ___XXXXX,XXXXXXXX,XX______,________,
  ________,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  _______X,X_______,XX______,________,
  ______XX,________,XX______,________,
  _____XXX,________,XX______,________,
  ____XXX_,_______X,XX______,________,
  ___XXX__,__XXXXXX,X_______,________,
  _XXXX___,__XXXXXX,________,________,
  __X_____,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_5EA6[112] = { /* code 5EA6 */
  ________,________,________,________,
  ________,________,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,____XX__,________,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,________,
  ___X____,________,________,________,
  ___X____,XX______,XX______,________,
  ___X_XXX,XXXXXXXX,XXXXXX__,________,
  ___X_XXX,XXXXXXXX,XXXXXX__,________,
  ___X____,XX______,XX______,________,
  ___X____,XXXXXXXX,XX______,________,
  ___X____,XXXXXXXX,XX______,________,
  ___X____,XX______,XX______,________,
  ___X____,________,________,________,
  __XX__XX,XXXXXXXX,XXXX____,________,
  __XX__XX,XXXXXXXX,XXXX____,________,
  __XX____,XX______,_XX_____,________,
  __XX____,_XX____X,XX______,________,
  __XX____,__XXX_XX,X_______,________,
  _XX_____,___XXXX_,________,________,
  _XX_____,XXXXXXXX,XX______,________,
  XX__XXXX,XXX____X,XXXXXX__,________,
  _X__XXX_,________,___XXX__,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_5FAE[112] = { /* code 5FAE */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XX__,__X_____,_XX_____,________,
  ____XX__,__X_____,_X______,________,
  ___XX__X,__X__XX_,_X______,________,
  ___XX__X,__X__XX_,_X______,________,
  __XX___X,__X__XX_,XXXXXXX_,________,
  _XX____X,__X__XX_,XXXXXXX_,________,
  _X__XX_X,XXXXXXX_,X___XX__,________,
  ____XX_X,XXXXXXX_,X___X___,________,
  ___XX___,_____XXX,X___X___,________,
  ___XX___,_______X,X___X___,________,
  __XX___X,XXXXXXXX,XX__X___,________,
  _XXX___X,XXXXXX__,XX_XX___,________,
  _XXX____,________,_X_XX___,________,
  XX_X___X,XXXXX___,_X_X____,________,
  ___X___X,XXXXX___,_XXX____,________,
  ___X___X,X___X__X,_XXX____,________,
  ___X___X,X___X_XX,__XX____,________,
  ___X___X,X___XXX_,_XXX____,________,
  ___X___X,___XXX__,XX_XX___,________,
  ___X__XX,____X___,X___XX__,________,
  ___X__X_,_______X,X___XXX_,________,
  ___X____,______XX,_____X__,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_65F6[112] = { /* code 65F6 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,__XX____,________,
  ________,________,__XX____,________,
  _XXXXXXX,X_______,__XX____,________,
  _XXXXXXX,X_______,__XX____,________,
  _XX____X,X_______,__XX____,________,
  _XX____X,X_XXXXXX,XXXXXXX_,________,
  _XX____X,X_XXXXXX,XXXXXXX_,________,
  _XX____X,X_______,__XX____,________,
  _XX____X,X_______,__XX____,________,
  _XXXXXXX,X__XX___,__XX____,________,
  _XXXXXXX,X__XX___,__XX____,________,
  _XX____X,X___XX__,__XX____,________,
  _XX____X,X___XX__,__XX____,________,
  _XX____X,X___XXX_,__XX____,________,
  _XX____X,X____X__,__XX____,________,
  _XX____X,X_______,__XX____,________,
  _XXXXXXX,X_______,__XX____,________,
  _XXXXXXX,X_______,__XX____,________,
  _XX____X,X_______,_XX_____,________,
  _XX____X,X____XXX,XXX_____,________,
  ________,_____XXX,XXX_____,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_6790[112] = { /* code 6790 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XX__,________,________,________,
  ____XX__,________,_XXXX___,________,
  ____XX__,__XXXXXX,XXXXXX__,________,
  ____XX__,__XXXXXX,XX______,________,
  ____XX__,__XX____,________,________,
  _XXXXXXX,X_XX____,________,________,
  _X__XXXX,X_XX____,________,________,
  ___XXX__,__XX____,________,________,
  ___XXXX_,__XX____,________,________,
  ___XXXXX,__XXXXXX,XXXXXXX_,________,
  __XXXXXX,__XXXXXX,XXXXXXX_,________,
  __X_XX_X,X_XX____,_X______,________,
  _XX_XX__,X_XX____,_X______,________,
  _X__XX__,__XX____,_X______,________,
  _X__XX__,__XX____,_X______,________,
  ____XX__,__X_____,_X______,________,
  ____XX__,_XX_____,_X______,________,
  ____XX__,_XX_____,_X______,________,
  ____XX__,_X______,_X______,________,
  ____XX__,XX______,_X______,________,
  ____XX_X,X_______,_X______,________,
  ____XX_X,________,_X______,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_6C27[112] = { /* code 6C27 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XX__,________,________,________,
  ____XX__,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XX___,________,________,________,
  ___X____,________,________,________,
  __XX_XXX,XXXXXXXX,XXXX____,________,
  __X_____,________,________,________,
  _XX_____,________,________,________,
  _X_XXXXX,XXXXXXXX,XXX_____,________,
  ____XX__,___XX___,_XX_____,________,
  _____XX_,___XX___,_XX_____,________,
  _____XX_,__XX____,_XX_____,________,
  _XXXXXXX,XXXXXXXX,_XX_____,________,
  ________,XX______,_XX_____,________,
  ________,XX______,_XX_____,________,
  __XXXXXX,XXXXXXX_,_XX_____,________,
  ________,XX______,_XX__X__,________,
  ________,XX______,__X__XX_,________,
  _XXXXXXX,XXXXXXXX,X_X__X__,________,
  ________,XX______,__XX_X__,________,
  ________,XX______,__XXXX__,________,
  ________,XX______,___XXX__,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_6D41[112] = { /* code 6D41 */
  ________,________,________,________,
  ________,________,________,________,
  ________,_____X__,________,________,
  __X_____,_____XX_,________,________,
  __XX____,_____XX_,________,________,
  ___XXX_X,XXXXXXXX,XXXXXX__,________,
  ____X__X,XXXXXXXX,XXXXXX__,________,
  ________,___XX___,________,________,
  ________,__XX____,_X______,________,
  _X______,_XX_____,_XX_____,________,
  _XXX___X,XX______,__XX____,________,
  __XXX__X,XXXXXXXX,XXXXX___,________,
  ___X___X,XXXXXXXX,XXXXXX__,________,
  ________,________,____X___,________,
  ________,XX___X__,_XX_____,________,
  ___XX___,XX___X__,_XX_____,________,
  ___XX___,XX___X__,_XX_____,________,
  ___XX___,XX___X__,_XX_____,________,
  ___X____,XX___X__,_XX__X__,________,
  __XX____,XX___X__,_XX__XX_,________,
  __XX___X,X____X__,_XX__XX_,________,
  __XX___X,X____X__,_XX__XX_,________,
  __XX_XXX,_____X__,_XXXXX__,________,
  _XX_XXX_,_____X__,__XXXX__,________,
  _XX__X__,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_6D53[112] = { /* code 6D53 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  __X_____,______X_,________,________,
  __XX____,_____XX_,________,________,
  ___XXX__,_____XX_,________,________,
  ____X__X,XXXXXXXX,XXXXXX__,________,
  _______X,XXXXXXXX,XXXXXX__,________,
  _______X,X___XX__,____XX__,________,
  _X_____X,X___XXX_,____XX__,________,
  _XXX___X,X__XXXX_,____XX__,________,
  __XXX___,___XX_X_,________,________,
  ___XX___,__XX__XX,____X___,________,
  ________,__XX__XX,__XXX___,________,
  ________,_XX____X,_XXX____,________,
  ___XX___,XXX____X,XX______,________,
  ___XX__X,X_X_____,X_______,________,
  ___XX_XX,X_X_____,XX______,________,
  ___XXXXX,__X_____,_XX_____,________,
  __XX__X_,__X_____,_XXX____,________,
  __XX____,__X___XX,__XXX___,________,
  __XX____,__X_XXXX,___XXX__,________,
  __XX____,__XXXX__,____XX__,________,
  _XX_____,_XXX____,________,________,
  _XX_____,__X_____,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_6E29[112] = { /* code 6E29 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  __X_____,________,________,________,
  _XXX____,XXXXXXXX,XXXX____,________,
  __XXX___,XXXXXXXX,XXXX____,________,
  ___XXX__,XX______,__XX____,________,
  ____X___,XXXXXXXX,XXXX____,________,
  ________,XXXXXXXX,XXXX____,________,
  _X______,XX______,__XX____,________,
  _XXX____,XXXXXXXX,XXXX____,________,
  __XXX___,XXXXXXXX,XXXX____,________,
  ___XX___,XX______,__XX____,________,
  ________,________,________,________,
  _______X,XXXXXXXX,XXXXX___,________,
  ___X___X,XXXXXXXX,XXXXX___,________,
  ___XX__X,X__XX__X,X__XX___,________,
  ___XX__X,X__XX__X,X__XX___,________,
  __XX___X,X__XX__X,X__XX___,________,
  __XX___X,X__XX__X,X__XX___,________,
  __XX___X,X__XX__X,X__XX___,________,
  __XX___X,X__XX__X,X__XX___,________,
  _XX__XXX,XXXXXXXX,XXXXXXX_,________,
  _XX__XXX,XXXXXXXX,XXXXXXX_,________,
  _XX_____,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_91CF[112] = { /* code 91CF */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXX_____,________,
  ____XX__,________,__X_____,________,
  ____XXXX,XXXXXXXX,XXX_____,________,
  ____XX__,________,__X_____,________,
  ____XXXX,XXXXXXXX,XXX_____,________,
  ____XX__,________,__X_____,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ____XXXX,XXXXXXXX,XXX_____,________,
  ____X___,___X____,__X_____,________,
  ____XXXX,XXXXXXXX,XXX_____,________,
  ____X___,___X____,__X_____,________,
  ____X___,___X____,__X_____,________,
  ____XXXX,XXXXXXXX,XXX_____,________,
  ____X___,___X____,__X_____,________,
  ________,___X____,________,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  ________,___X____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontYaHei_Mono28_95F4[112] = { /* code 95F4 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ___XX___,________,________,________,
  ___XXX__,_XXXXXXX,XXXXXX__,________,
  ____XXX_,_XXXXXXX,XXXXXX__,________,
  _____X__,________,____XX__,________,
  _XX_____,________,____XX__,________,
  _XX_____,________,____XX__,________,
  _XX____X,XXXXXXXX,____XX__,________,
  _XX____X,XXXXXXXX,____XX__,________,
  _XX____X,_______X,____XX__,________,
  _XX____X,_______X,____XX__,________,
  _XX____X,XXXXXXXX,____XX__,________,
  _XX____X,XXXXXXXX,____XX__,________,
  _XX____X,_______X,____XX__,________,
  _XX____X,_______X,____XX__,________,
  _XX____X,_______X,____XX__,________,
  _XX____X,XXXXXXXX,____XX__,________,
  _XX____X,XXXXXXXX,____XX__,________,
  _XX____X,________,____XX__,________,
  _XX_____,________,____XX__,________,
  _XX_____,________,____XX__,________,
  _XX_____,_______X,XXXXX___,________,
  _XX_____,_______X,XXXXX___,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontYaHei_Mono28_CharInfo[12] = {
   {  26,  26,  4, acGUI_FontYaHei_Mono28_4EEA } /* code 4EEA */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_5206 } /* code 5206 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_5EA6 } /* code 5EA6 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_5FAE } /* code 5FAE */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_65F6 } /* code 65F6 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_6790 } /* code 6790 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_6C27 } /* code 6C27 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_6D41 } /* code 6D41 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_6D53 } /* code 6D53 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_6E29 } /* code 6E29 */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_91CF } /* code 91CF */
  ,{  26,  26,  4, acGUI_FontYaHei_Mono28_95F4 } /* code 95F4 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop12 = {
   0x95F4 /* first character */
  ,0x95F4 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[ 11] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop11 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[ 10] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop10 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  9] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop9 = {
   0x6D53 /* first character */
  ,0x6D53 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  8] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop8 = {
   0x6D41 /* first character */
  ,0x6D41 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  7] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop7 = {
   0x6C27 /* first character */
  ,0x6C27 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  6] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop6 = {
   0x6790 /* first character */
  ,0x6790 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  5] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop5 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  4] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop4 = {
   0x5FAE /* first character */
  ,0x5FAE /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  3] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop3 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  2] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop2 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  1] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontYaHei_Mono28_Prop1 = {
   0x4EEA /* first character */
  ,0x4EEA /* last character  */
  ,&GUI_FontYaHei_Mono28_CharInfo[  0] /* address of first character */
  ,&GUI_FontYaHei_Mono28_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontYaHei_Mono28 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,28 /* height of font  */
  ,28 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontYaHei_Mono28_Prop1}
  ,22 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

