/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Button_YaHei_Mono18.c                                 *
* Font:        Microsoft YaHei Mono                                  *
* Height:      18                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  18                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\9. Œ¢—ı∑÷Œˆ“«_STM32\Code-By-G_Z\3. Œ¢—ı∑÷Œˆ“«V0.1\STemWinLibrary522\Font\button.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontButton_YaHei_Mono18;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontButton_YaHei_Mono18_7A0B[ 36] = { /* code 7A0B */
  ________,________,
  ________,________,
  ___XXXXX,XXXXXX__,
  _XXX__XX,_____X__,
  ___X__XX,_____X__,
  ___X__XX,XXXXXX__,
  XXXXXXXX,_____X__,
  __XX____,________,
  __XXX_XX,XXXXXX__,
  _X_XX___,_XX_____,
  _X_X_X__,_XX_____,
  X__X__XX,XXXXXX__,
  X__X____,_XX_____,
  ___X____,_XX_____,
  ___X_XXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontButton_YaHei_Mono18_7F6E[ 36] = { /* code 7F6E */
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  _XX__X__,_X__X___,
  _XXXXXXX,XXXXX___,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontButton_YaHei_Mono18_8BBE[ 36] = { /* code 8BBE */
  ________,________,
  ________,________,
  __X____X,XXXXX___,
  __XX___X,___XX___,
  ___X__XX,___XX___,
  _____XX_,___XX___,
  XXX__X__,____XXX_,
  __X_____,________,
  __X__XXX,XXXXX___,
  __X___X_,____X___,
  __X____X,___X____,
  __X_X___,X_X_____,
  __XXX___,XX______,
  __X___XX,__XXX___,
  ____XX__,____XX__,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontButton_YaHei_Mono18_91CF[ 36] = { /* code 91CF */
  ________,________,
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  XXXXXXXX,XXXXXXX_,
  __XX___X,____X___,
  __XXXXXX,XXXXX___,
  __XX___X,____X___,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontButton_YaHei_Mono18_CharInfo[4] = {
   {  15,  15,  2, acGUI_FontButton_YaHei_Mono18_7A0B } /* code 7A0B */
  ,{  15,  15,  2, acGUI_FontButton_YaHei_Mono18_7F6E } /* code 7F6E */
  ,{  15,  15,  2, acGUI_FontButton_YaHei_Mono18_8BBE } /* code 8BBE */
  ,{  15,  15,  2, acGUI_FontButton_YaHei_Mono18_91CF } /* code 91CF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontButton_YaHei_Mono18_Prop4 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_FontButton_YaHei_Mono18_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontButton_YaHei_Mono18_Prop3 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontButton_YaHei_Mono18_CharInfo[  2] /* address of first character */
  ,&GUI_FontButton_YaHei_Mono18_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontButton_YaHei_Mono18_Prop2 = {
   0x7F6E /* first character */
  ,0x7F6E /* last character  */
  ,&GUI_FontButton_YaHei_Mono18_CharInfo[  1] /* address of first character */
  ,&GUI_FontButton_YaHei_Mono18_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontButton_YaHei_Mono18_Prop1 = {
   0x7A0B /* first character */
  ,0x7A0B /* last character  */
  ,&GUI_FontButton_YaHei_Mono18_CharInfo[  0] /* address of first character */
  ,&GUI_FontButton_YaHei_Mono18_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontButton_YaHei_Mono18 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontButton_YaHei_Mono18_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

