/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Microsoft YaHei Mono28.c                              *
* Font:        Microsoft YaHei Mono                                  *
* Height:      28                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  28                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: F:\MDK_STM32\9. Œ¢—ı∑÷Œˆ“«_STM32\Code-By-G_Z\3. Œ¢—ı∑÷Œˆ“«V0.1\STemWinLibrary522\Font\njtech.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftYaHeiMono28;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono28_4E1A[112] = { /* code 4E1A */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  __X_____,XX___XX_,____X___,________,
  __XX____,XX___XX_,___XX___,________,
  __XX____,XX___XX_,___XX___,________,
  __XX____,XX___XX_,___XX___,________,
  ___XX___,XX___XX_,__XX____,________,
  ___XX___,XX___XX_,__XX____,________,
  ____XX__,XX___XX_,_XX_____,________,
  ____XX__,XX___XX_,_XX_____,________,
  ____XX__,XX___XX_,_X______,________,
  _____X__,XX___XX_,_X______,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  ________,XX___XX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono28_4EAC[112] = { /* code 4EAC */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,__X_____,________,________,
  ________,__XX____,________,________,
  ________,___XX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXXX____,________,
  ___XX___,________,__XX____,________,
  ___XX___,________,__XX____,________,
  ___XX___,________,__XX____,________,
  ___XXXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXXX____,________,
  ___XX___,___XX___,__XX____,________,
  ________,___XX___,________,________,
  ______X_,___XX__X,X_______,________,
  ____XXX_,___XX___,XX______,________,
  ___XXX__,___XX___,_XXX____,________,
  __XXX___,___XX___,__XXX___,________,
  _XX_____,___XX___,___XXX__,________,
  _X_____X,XXXX____,____X___,________,
  _______X,XXXX____,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono28_5357[112] = { /* code 5357 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  __XX___X,X_____XX,___XX___,________,
  __XX___X,XX____XX,___XX___,________,
  __XX____,XX___XX_,___XX___,________,
  __XX_XXX,XXXXXXXX,XX_XX___,________,
  __XX____,___X____,___XX___,________,
  __XX____,___X____,___XX___,________,
  __XX____,___X____,___XX___,________,
  __XX____,___X____,___XX___,________,
  __XX_XXX,XXXXXXXX,XX_XX___,________,
  __XX____,___X____,___XX___,________,
  __XX____,___X____,___XX___,________,
  __XX____,___X____,___XX___,________,
  __XX____,___X___X,XXXXX___,________,
  __XX____,___X___X,XXXX____,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono28_5927[112] = { /* code 5927 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,__XX____,________,________,
  ________,__XXX___,________,________,
  ________,__XXX___,________,________,
  ________,__X_X___,________,________,
  ________,_XX_XX__,________,________,
  ________,_XX_XX__,________,________,
  ________,XX___XX_,________,________,
  _______X,XX___XXX,________,________,
  ______XX,X_____XX,________,________,
  _____XXX,_______X,XX______,________,
  ____XXX_,________,XXX_____,________,
  __XXXX__,________,_XXXX___,________,
  _XXX____,________,__XXXXX_,________,
  _XX_____,________,____XX__,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono28_5B66[112] = { /* code 5B66 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,__X_____,__X_____,________,
  ____X___,__XX____,_XXX____,________,
  ____XX__,__XXX___,_XX_____,________,
  ____XXX_,___X____,XX______,________,
  _____X__,________,X_______,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XX_____,________,____XX__,________,
  _XX_____,________,____XX__,________,
  _XX__XXX,XXXXXXXX,XX__XX__,________,
  _____XXX,XXXXXXXX,XX______,________,
  ________,______XX,X_______,________,
  ________,____XXXX,________,________,
  ________,___XXX__,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  ________,___XX___,________,________,
  _______X,XXXXX___,________,________,
  _______X,XXXX____,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMicrosoftYaHeiMono28_5DE5[112] = { /* code 5DE5 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXXXXXXX,XXXXX___,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  ________,__XX____,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXX__,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMicrosoftYaHeiMono28_CharInfo[6] = {
   {  26,  26,  4, acGUI_FontMicrosoftYaHeiMono28_4E1A } /* code 4E1A */
  ,{  26,  26,  4, acGUI_FontMicrosoftYaHeiMono28_4EAC } /* code 4EAC */
  ,{  26,  26,  4, acGUI_FontMicrosoftYaHeiMono28_5357 } /* code 5357 */
  ,{  26,  26,  4, acGUI_FontMicrosoftYaHeiMono28_5927 } /* code 5927 */
  ,{  26,  26,  4, acGUI_FontMicrosoftYaHeiMono28_5B66 } /* code 5B66 */
  ,{  26,  26,  4, acGUI_FontMicrosoftYaHeiMono28_5DE5 } /* code 5DE5 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono28_Prop6 = {
   0x5DE5 /* first character */
  ,0x5DE5 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono28_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono28_Prop5 = {
   0x5B66 /* first character */
  ,0x5B66 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono28_CharInfo[  4] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono28_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono28_Prop4 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono28_CharInfo[  3] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono28_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono28_Prop3 = {
   0x5357 /* first character */
  ,0x5357 /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono28_CharInfo[  2] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono28_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono28_Prop2 = {
   0x4EAC /* first character */
  ,0x4EAC /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono28_CharInfo[  1] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono28_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMicrosoftYaHeiMono28_Prop1 = {
   0x4E1A /* first character */
  ,0x4E1A /* last character  */
  ,&GUI_FontMicrosoftYaHeiMono28_CharInfo[  0] /* address of first character */
  ,&GUI_FontMicrosoftYaHeiMono28_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMicrosoftYaHeiMono28 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,28 /* height of font  */
  ,28 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMicrosoftYaHeiMono28_Prop1}
  ,22 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

